"""3rd party wrappers for the environments including Pettingzoo, BenchMarl, and RLLIB."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03b_wrappers.external.ipynb.

# %% ../../nbs/03b_wrappers.external.ipynb #6b238804
from __future__ import annotations

import gymnasium as gym

from gymnasium import spaces
from pettingzoo import ParallelEnv
from typing import Any

from ..envs.base import AgentID, MultiGridEnv


import gymnasium as gym

from ray.rllib.env import MultiAgentEnv
from ray.tune.registry import register_env

from ..envs.base import MultiGridEnv
from ..envs import CONFIGURATIONS
from .base import OneHotObsWrapper


# %% auto #0
__all__ = ['PettingZooWrapper', 'to_pettingzoo_env', 'RLlibWrapper', 'to_rllib_env']

# %% ../../nbs/03b_wrappers.external.ipynb #b6c1578d
class PettingZooWrapper(ParallelEnv):
    """
    Wrapper for a ``MultiGridEnv`` environment that implements the
    PettingZoo ``ParallelEnv`` interface.
    """

    def __init__(self, env: MultiGridEnv):
        self.env = env
        self.reset = self.env.reset
        self.step = self.env.step
        self.render = self.env.render
        self.close = self.env.close
        self.metadata = {}

    @property
    def agents(self) -> list[AgentID]:
        if self.env.is_done():
            return []
        return [agent.index for agent in self.env.agents if not agent.terminated]

    @property
    def possible_agents(self) -> list[AgentID]:
        return [agent.index for agent in self.env.agents]

    @property
    def observation_spaces(self) -> dict[AgentID, spaces.Space]:
        return dict(self.env.observation_space)

    @property
    def action_spaces(self) -> dict[AgentID, spaces.Space]:
        return dict(self.env.action_space)

    @property
    def render_mode(self) -> str | None:
        return self.env.render_mode

    def observation_space(self, agent_id: AgentID) -> spaces.Space:
        return self.env.observation_space[agent_id]

    def action_space(self, agent_id: AgentID) -> spaces.Space:
        return self.env.action_space[agent_id]


# %% ../../nbs/03b_wrappers.external.ipynb #c527053f
def to_pettingzoo_env(
    env_cls: type[MultiGridEnv],
    *wrappers: gym.Wrapper,
    metadata: dict[str, Any] = {}) -> type[ParallelEnv]:
    """
    Convert a ``MultiGridEnv`` environment class to a PettingZoo ``ParallelEnv`` class.

    Note that this is a wrapper around the environment **class**,
    not environment instances.

    Parameters
    ----------
    env_cls : type[MultiGridEnv]
        ``MultiGridEnv`` environment class
    wrappers : gym.Wrapper
        Gym wrappers to apply to the environment
    metadata : dict[str, Any]
        Environment metadata

    Returns
    -------
    pettingzoo_env_cls : type[ParallelEnv]
        PettingZoo ``ParallelEnv`` environment class
    """
    class PettingZooEnv(PettingZooWrapper):
        def __init__(self, *args, **kwargs):
            env = env_cls(*args, **kwargs)
            for wrapper in wrappers:
                env = wrapper(env)
            super().__init__(env)

    PettingZooEnv.__name__ = f"PettingZoo_{env_cls.__name__}"
    PettingZooEnv.metadata = metadata
    return PettingZooEnv


# %% ../../nbs/03b_wrappers.external.ipynb #553cea40
class RLlibWrapper(MultiAgentEnv):
    """
    Wrapper for a ``MultiGridEnv`` environment that implements the
    RLlib ``MultiAgentEnv`` interface.
    """

    def __init__(self, env: MultiGridEnv):
        super().__init__()
        self.env = env
        self.agents = list(range(len(env.unwrapped.agents)))
        self.possible_agents = self.agents[:]

    def reset(self, *args, **kwargs):
        return self.env.reset(*args, **kwargs)

    def step(self, *args, **kwargs):
        obs, rewards, terminations, truncations, infos = self.env.step(*args, **kwargs)
        terminations['__all__'] = all(terminations.values())
        truncations['__all__'] = all(truncations.values())
        return obs, rewards, terminations, truncations, infos

    def get_observation_space(self, agent_index: int):
        return self.env.unwrapped.agents[agent_index].observation_space

    def get_action_space(self, agent_index: int):
        return self.env.unwrapped.agents[agent_index].action_space
    

# %% ../../nbs/03b_wrappers.external.ipynb #08f57dbe
def to_rllib_env(
    env_cls: type[MultiGridEnv],
    *wrappers: gym.Wrapper,
    default_config: dict = {}) -> type[MultiAgentEnv]:
    """
    Convert a ``MultiGridEnv`` environment class to an RLLib ``MultiAgentEnv`` class.

    Note that this is a wrapper around the environment **class**,
    not environment instances.

    Parameters
    ----------
    env_cls : type[MultiGridEnv]
        ``MultiGridEnv`` environment class
    wrappers : gym.Wrapper
        Gym wrappers to apply to the environment
    default_config : dict
        Default configuration for the environment

    Returns
    -------
    rllib_env_cls : type[MultiAgentEnv]
        RLlib ``MultiAgentEnv`` environment class
    """
    class RLlibEnv(RLlibWrapper):
        def __init__(self, config: dict = {}):
            config = {**default_config, **config}
            env = env_cls(**config)
            for wrapper in wrappers:
                env = wrapper(env)
            super().__init__(env)

    RLlibEnv.__name__ = f"RLlib_{env_cls.__name__}"
    return RLlibEnv


