"""3rd party wrappers for the environments including Pettingzoo, BenchMarl, and RLLIB."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03b_wrappers.external.ipynb.

# %% ../../nbs/03b_wrappers.external.ipynb #6b238804
from __future__ import annotations

import gymnasium as gym

from gymnasium import spaces
from pettingzoo import ParallelEnv
from typing import Any

from ..envs.base import AgentID, MultiGridEnv


import gymnasium as gym

from ray.rllib.env import MultiAgentEnv
from ray.tune.registry import register_env

from ..envs.base import MultiGridEnv
from ..envs import CONFIGURATIONS
from .base import OneHotObsWrapper


# %% auto #0
__all__ = ['AgentID', 'ObsType', 'ActionType', 'PettingZooWrapper', 'to_pettingzoo_env', 'TorchRLPettingZooWrapper',
           'RLlibWrapper', 'to_rllib_env']

# %% ../../nbs/03b_wrappers.external.ipynb #53cd2e2e
from typing import Any, TypeVar
import numpy as np

# %% ../../nbs/03b_wrappers.external.ipynb #4e330534
# ActionType = TypeVar("ActionType")
AgentID = int
ObsType = dict[str, Any]
ActionType = Any

# %% ../../nbs/03b_wrappers.external.ipynb #b6c1578d
class PettingZooWrapper(ParallelEnv):
    """
    Wrapper for a ``MultiGridEnv`` environment that implements the
    PettingZoo ``ParallelEnv`` interface.
    """

    def __init__(self, env: MultiGridEnv):
        self.env = env
        # self.reset = self.env.reset
        # self.step = self.env.step
        # self.render = self.env.render
        # self.close = self.env.close
        self.metadata = {}

    # @property
    def is_done(self) -> bool:
        return self.env.unwrapped.is_done()
    
    def reset(
        self,
        seed: int | None = None,
        options: dict | None = None,
    ) -> tuple[dict[AgentID, ObsType], dict[AgentID, dict]]:
        return self.env.reset(seed=seed, options=options)
    
    def step(
        self, actions: dict[AgentID, ActionType]
    ) -> tuple[
        dict[AgentID, ObsType],
        dict[AgentID, float],
        dict[AgentID, bool],
        dict[AgentID, bool],
        dict[AgentID, dict[str, Any]],
    ]:
        return self.env.step(actions)
    
    def render(self) -> None | np.ndarray | str | list:
        return self.env.render()
    
    def close(self) -> None:
        return self.env.close()
    
    @property
    def agents(self) -> list[AgentID]:
        if self.env.unwrapped.is_done():
            return []
        return [agent.index for agent in self.env.unwrapped.agents if not agent.terminated]

    @property
    def possible_agents(self) -> list[AgentID]:
        return [agent.index for agent in self.env.unwrapped.agents]

    @property
    def observation_spaces(self) -> dict[AgentID, spaces.Space]:
        return dict(self.env.observation_space)

    @property
    def action_spaces(self) -> dict[AgentID, spaces.Space]:
        return dict(self.env.action_space)

    @property
    def render_mode(self) -> str | None:
        return self.env.render_mode

    def observation_space(self, agent_id: AgentID) -> spaces.Space:
        return self.env.observation_space[agent_id]

    def action_space(self, agent_id: AgentID) -> spaces.Space:
        return self.env.action_space[agent_id]


# %% ../../nbs/03b_wrappers.external.ipynb #c527053f
def to_pettingzoo_env(
    env_cls: type[MultiGridEnv],
    *wrappers: gym.Wrapper,
    metadata: dict[str, Any] = {}) -> type[ParallelEnv]:
    """
    Convert a ``MultiGridEnv`` environment class to a PettingZoo ``ParallelEnv`` class.

    Note that this is a wrapper around the environment **class**,
    not environment instances.

    Parameters
    ----------
    env_cls : type[MultiGridEnv]
        ``MultiGridEnv`` environment class
    wrappers : gym.Wrapper
        Gym wrappers to apply to the environment
    metadata : dict[str, Any]
        Environment metadata

    Returns
    -------
    pettingzoo_env_cls : type[ParallelEnv]
        PettingZoo ``ParallelEnv`` environment class
    """
    class PettingZooEnv(PettingZooWrapper):
        def __init__(self, *args, **kwargs):
            env = env_cls(*args, **kwargs)
            for wrapper in wrappers:
                env = wrapper(env)
            super().__init__(env)

    PettingZooEnv.__name__ = f"PettingZoo_{env_cls.__name__}"
    PettingZooEnv.metadata = metadata
    return PettingZooEnv


# %% ../../nbs/03b_wrappers.external.ipynb #fda9038e
class TorchRLPettingZooWrapper(PettingZooWrapper):
    """
    Extends PettingZooWrapper with string agent IDs required by TorchRL.
    """
    def __init__(self, env: MultiGridEnv):
        # Don't call super().__init__() — we don't want the instance attribute assignments
        self.env = env
        self.metadata = {}

    def _remap_keys(self, d: dict) -> dict:
        """Convert integer agent keys to string agent IDs."""
        return {self._agent_id(k): v for k, v in d.items()}

    def reset(self, seed=None, options=None):
        observations, infos = self.env.reset(seed=seed, options=options)
        obs_remapped = self._remap_keys(observations)
        
        # TorchRL expects {agent_id: {}} for each agent, not just {}
        if not infos:
            infos_remapped = {self._agent_id(i): {} for i in range(len(observations))}
        else:
            infos_remapped = self._remap_keys(infos)
        
        return obs_remapped, infos_remapped
    
    def step(self, actions):
        # Remap string agent IDs back to integer keys for the underlying env
        int_actions = {self._agent_index(k): v for k, v in actions.items()}
        observations, rewards, terminations, truncations, infos = self.env.step(int_actions)
        return (
            self._remap_keys(observations),
            self._remap_keys(rewards),
            self._remap_keys(terminations),
            self._remap_keys(truncations),
            self._remap_keys(infos),
        )

    def _agent_id(self, index: int) -> str:
        return f"agent_{index}"

    def _agent_index(self, agent_id: str) -> int:
        return int(agent_id.split("_")[1])

    @property
    def agents(self) -> list[AgentID]:
        if self.env.unwrapped.is_done():
            return []
        return [self._agent_id(agent.index) 
                for agent in self.env.unwrapped.agents 
                if not agent.terminated]

    @property
    def possible_agents(self) -> list[AgentID]:
        return [self._agent_id(agent.index) 
                for agent in self.env.unwrapped.agents]

    @property
    def observation_spaces(self) -> dict[AgentID, spaces.Space]:
        return {self._agent_id(i): space 
                for i, space in dict(self.env.observation_space).items()}

    @property
    def action_spaces(self) -> dict[AgentID, spaces.Space]:
        return {self._agent_id(i): space 
                for i, space in dict(self.env.action_space).items()}

    def observation_space(self, agent_id: AgentID) -> spaces.Space:
        return self.env.observation_space[self._agent_index(agent_id)]

    def action_space(self, agent_id: AgentID) -> spaces.Space:
        return self.env.action_space[self._agent_index(agent_id)]

# %% ../../nbs/03b_wrappers.external.ipynb #553cea40
class RLlibWrapper(MultiAgentEnv):
    """
    Wrapper for a ``MultiGridEnv`` environment that implements the
    RLlib ``MultiAgentEnv`` interface.
    """

    def __init__(self, env: MultiGridEnv):
        super().__init__()
        self.env = env
        self.agents = list(range(len(env.unwrapped.agents)))
        self.possible_agents = self.agents[:]

    def reset(self, *args, **kwargs):
        return self.env.reset(*args, **kwargs)

    def step(self, *args, **kwargs):
        obs, rewards, terminations, truncations, infos = self.env.step(*args, **kwargs)
        terminations['__all__'] = all(terminations.values())
        truncations['__all__'] = all(truncations.values())
        return obs, rewards, terminations, truncations, infos

    def get_observation_space(self, agent_index: int):
        return self.env.unwrapped.agents[agent_index].observation_space

    def get_action_space(self, agent_index: int):
        return self.env.unwrapped.agents[agent_index].action_space
    

# %% ../../nbs/03b_wrappers.external.ipynb #08f57dbe
def to_rllib_env(
    env_cls: type[MultiGridEnv],
    *wrappers: gym.Wrapper,
    default_config: dict = {}) -> type[MultiAgentEnv]:
    """
    Convert a ``MultiGridEnv`` environment class to an RLLib ``MultiAgentEnv`` class.

    Note that this is a wrapper around the environment **class**,
    not environment instances.

    Parameters
    ----------
    env_cls : type[MultiGridEnv]
        ``MultiGridEnv`` environment class
    wrappers : gym.Wrapper
        Gym wrappers to apply to the environment
    default_config : dict
        Default configuration for the environment

    Returns
    -------
    rllib_env_cls : type[MultiAgentEnv]
        RLlib ``MultiAgentEnv`` environment class
    """
    class RLlibEnv(RLlibWrapper):
        def __init__(self, config: dict = {}):
            config = {**default_config, **config}
            env = env_cls(**config)
            for wrapper in wrappers:
                env = wrapper(env)
            super().__init__(env)

    RLlibEnv.__name__ = f"RLlib_{env_cls.__name__}"
    return RLlibEnv


