# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_configs.env.ipynb.

# %% auto #0
__all__ = ['MultiGridEnvConfig', 'RedBlueDoorsEnvConfig', 'PlaygroundEnvConfig', 'PettingZooWrapperConfig',
           'TorchRLWrapperConfig']

# %% ../../nbs/04_configs.env.ipynb #c9df5b42
from dataclasses import dataclass, field
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING
from typing import Any

# %% ../../nbs/04_configs.env.ipynb #9ad43e6c
@dataclass
class MultiGridEnvConfig:
    _target_: str = MISSING  # hydra instantiation target
    mission_space: str = "maximize reward"
    agents: int = 1
    grid_size: int | None = None
    width: int | None = None
    height: int | None = None
    max_steps: int = 100
    see_through_walls: bool = False
    agent_view_size: int = 7
    allow_agent_overlap: bool = True
    joint_reward: bool = False
    success_termination_mode: str = "all"
    failure_termination_mode: str = "all"
    render_mode: str | None = None
    screen_size: int = 640
    highlight: bool = True
    tile_size: int = 32
    agent_pov: bool = False

# %% ../../nbs/04_configs.env.ipynb #42a079e1
@dataclass
class RedBlueDoorsEnvConfig(MultiGridEnvConfig):
    _target_: str = "multigrid.envs.RedBlueDoorsEnv"
    grid_size: int = 8
    max_steps: int = 200

@dataclass
class PlaygroundEnvConfig(MultiGridEnvConfig):
    _target_: str = "multigrid.envs.PlaygroundEnv"
    grid_size: int = 11

@dataclass
class PettingZooWrapperConfig:
    _target_: str = "multigrid.wrappers.external.PettingZooWrapper"
    env: MultiGridEnvConfig = MISSING  # nested env config

@dataclass
class TorchRLWrapperConfig:
    _target_: str = "multigrid.wrappers.external.TorchRLPettingZooWrapper"
    env: MultiGridEnvConfig = MISSING
    return_state: bool = False
    group_map: Any = None


